app = "ecoflowmon"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  COLLECTION_INTERVAL = "60"
  METRICS_PORT = "9090"

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"

[[services]]
  protocol = "tcp"
  internal_port = 9090

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services.tcp_checks]]
  interval = "30s"
  timeout = "10s"
  grace_period = "5s"
