global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'ecoflow'
    static_configs:
      - targets: ['ecoflow-collector:9090']
        labels:
          instance: 'ecoflowmon'

  - job_name: 'smartmeter'
    static_configs:
      - targets: ['smartmeter-exporter:9091']
        labels:
          instance: 'smartmeter'
    scrape_interval: 300s
    scrape_timeout: 30s
